server:
  port: 8083

spring:
  cloud:
    gateway:
      routes:
        - id: Receiver
          uri: lb://Receiver
          predicates:            - Path=/receiver/**
         
        - id: Sender
          uri: lb://Sender
          predicates:            - Path=/sender/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost 